chore: savepoint for device swap

diff --git a/bin/macbuild b/bin/macbuild
--- a/bin/macbuild
+++ b/bin/macbuild
@@ -1,11 +1,15 @@
 #!/bin/bash
-# Initial macOS setup for configuration.
+# Initialize macOS for daily use by installing specified tools, and updating configurations.
 
 # Set values
-pkg=${0##*/}
-
-GIT_REPO="https://github.com/cgswong/macbuild.git"
-MB_HOME="/usr/local/macbuild"
+SCRIPT_NAME=${0##*/}
+MACBUILD_VERSION="1.0.0"
+MACBUILD_REPO=${MACBUILD_REPO:-"https://github.com/cgswong/macbuild.git"}
+MACBUILD_HOME=${MACBUILD_HOME:-"~/.macbuild"}
+MACBUILD_LOG_LEVEL=${MACBUILD_LOG_LEVEL:-"INFO"}
+MACBUILD_LOG_FILE=${MACBUILD_LOG_FILE:-"~/.macbuild/macbuild.log"}
+MACBUILD_UPDATE_FILE="homebrew.macbuild.brewupdate.plist"
+OS_UPDATE_DIR="/Library/LaunchDaemons"
 
 # set colors
 red=$(tput setaf 1)
@@ -17,46 +21,46 @@ cyan=$(tput setaf 6)
 white=$(tput setaf 7)
 reset=$(tput sgr0)
 
-# Print messages
+# Print messages to screen
 log() {
-  # Write messages to screen
-  echo "$(date +"%F %T") [${pkg}] $1"
-}
-
-# Print error message and exit
-die() {
-  log "${red}[FAIL] $1${reset}" >&2 && return 1
+  if [[ "${1}" == "DEBUG" ]]; then
+    echo "$(date +"%F %T") [${SCRIPT_NAME}] ${2}" >>${MACBUILD_LOG_FILE}
+  elif [[ "${1}" == "FAIL" ]]; then
+    echo "${red}$(date +"%F %T") ${2}${reset}"
+  else
+    echo "$(date +"%F %T") ${2}"
+  fi
 }
 
 # Print banner
 print_banner() {
-echo "${green}                         _             _  _      _${reset}"
-echo "${green} _ __ ___    __ _   ___ | |__   _   _ (_)| |  __| |${reset}"
-echo "${green}| '_ \` _ \  / _\` | / __|| '_ \ | | | || || | / _\` |${reset}"
-echo "${green}| | | | | || (_| || (__ | |_) || |_| || || || (_| |${reset}"
-echo "${green}|_| |_| |_| \__,_| \___||_.__/  \__,_||_||_| \__,_|${reset}"
-
+  echo "${green}                         _             _  _      _    ${reset}"
+  echo "${green} _ __ ___    __ _   ___ | |__   _   _ (_)| |  __| |   ${reset}"
+  echo "${green}| '_ \` _ \  / _\` | / __|| '_ \ | | | || || | / _\` |${reset}"
+  echo "${green}| | | | | || (_| || (__ | |_) || |_| || || || (_| |   ${reset}"
+  echo "${green}|_| |_| |_| \__,_| \___||_.__/  \__,_||_||_| \__,_|   ${reset} v${MACBUILD_VERSION}"
+  echo ""
 }
 
 usage() {
   print_banner
-cat <<EOM
+  cat <<-EOM
 
 ---------------------
 
-${pkg} - Install and configure macOS computer.
+${SCRIPT_NAME} - Install tools and configure macOS computer.
 
-Usage: ${pkg} [options]
+Usage: ${SCRIPT_NAME} [options]
 
 Options:
   -h, --help
       Output help (this message)
 
   -i, --install
-      Install ${pkg} only.
+      Install ${SCRIPT_NAME} only.
 
   -r=, --repo=[github_repo]
-      GitHub repository to use (defaults to ${GIT_REPO}).
+      GitHub repository to use for remote configuration (defaults to ${MACBUILD_REPO}).
 
   -t=, --tags=[ansible tags]
       Comma separated list of tags to use for filtering setup. Valid tags are:
@@ -69,75 +73,73 @@ Options:
 EOM
 }
 
-# Get and install Xcode CLI tools (credits https://github.com/boxcutter/osx/blob/master/script/xcode-cli-tools.sh)
-install_clt() {
-  OSX_VERS=$(sw_vers -productVersion | awk -F "." '{print $2}')
-
-  # on 10.9+, we can leverage SUS to get the latest CLI tools
-  if [ "$OSX_VERS" -ge 9 ]; then
-    # Create the placeholder file that's checked by CLI updates' .dist code in Apple's SUS catalog
-    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
-    # find the CLI Tools update
-    PROD=$(softwareupdate -l | grep "\*.*Command Line" | head -n 1 | awk -F"*" '{print $2}' | sed -e 's/^ *//' | tr -d '\n')
-    # Install it
-    softwareupdate -i "$PROD" -v
-    rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
-  fi
-}
-
 main() {
-  log "Checking if we need to ask for a sudo password"
+  mkdir -p ${MACBUILD_HOME}
+  log DEBUG "Checking if we need to ask for a password to use SUDO."
   sudo -v
   export BECOME_ASK_PASS=True
 
-  log "Keep-alive: update existing sudo time stamp until we are finished"
-  while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
+  log DEBUG "Keep-alive: Updating existing SUDO time stamp until we are finished."
+  while true; do
+    sudo -n true
+    sleep 60
+    kill -0 "$$" || exit
+  done 2>/dev/null &
 
   export HOMEBREW_CASK_OPTS="--appdir=/Applications"
 
   # Install XCode command line tools
   if [[ ! -f "/Library/Developer/CommandLineTools/usr/bin/clang" ]]; then
-    log "Installing XCode command line tools"
-    install_clt
+    log INFO "Installing XCode command line tools."
+    xcode-select --install
   fi
 
-  # Install Ansible
-  if ! which pip &>/dev/null ; then
-    log "Installing PIP"
-    sudo easy_install --quiet pip
-  fi
-  if ! which ansible &>/dev/null; then
-      log "Installing Ansible"
-      sudo -H pip install --upgrade --quiet ansible
-  fi
-
-  # Create directories and files
-  if [[ ! -d ${MB_HOME} ]]; then
-    log "Creating necessary folders"
-    sudo mkdir -p ${MB_HOME}
-    sudo chown -R ${USER} ${MB_HOME}
+  # Install Python packages
+  if command -V python3 &>/dev/null; then
+    log INFO "Installing pipx and Python packages."
+    python3 -m pip install --upgrade pipx
+    if [[ -r ${MACBUILD_HOME}/pipx_packages.lst ]]; then
+      for pkg in $(cat ${MACBUILD_HOME}/pipx_packages.lst); do
+        pipx install ${pkg}
+      done
+    fi
   fi
 
-  if [ ! -z ${MB_INSTALL} ]; then
-    log "Installing ${pkg}"
-    git clone -q ${GIT_REPO} ${MB_HOME}
-    ln -sf ${MB_HOME}/bin/macbuild /usr/local/bin/macbuild
-    exit 0
+  # Install Homebrew
+  if ! command -V brew &>/dev/null; then
+    log INFO "Installing Homebrew <https://brew.sh/>."
+    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+    if [[ ! -f ${OS_UPDATE_DIR}/${MACBUILD_UPDATE_FILE} ]]; then
+      log INFO "Setting up Homebrew auto-update using Launchd"
+      cp ${MACBUILD_HOME}/${MACBUILD_UPDATE_FILE} ${OS_UPDATE_DIR}/
+      sudo chmod 0644 ${OS_UPDATE_DIR}/${MACBUILD_UPDATE_FILE}
+      sudo chown root ${OS_UPDATE_DIR}/${MACBUILD_UPDATE_FILE}
+      sudo launchctl unload ${OS_UPDATE_DIR}/${MACBUILD_UPDATE_FILE} && sudo launchctl load ${OS_UPDATE_DIR}/${MACBUILD_UPDATE_FILE}
+      sudo launchctl stop ${MACBUILD_UPDATE_FILE} && sudo launchctl start ${MACBUILD_UPDATE_FILE}
+    fi
   fi
 
-  # Run Ansible roles
-  CWD=${PWD}
-  cd ${MB_HOME}
-  log "Getting required roles"
-  ansible-galaxy install --role-file=requirements.yml --roles-path=${MB_HOME}/roles
-
-  log "Running Ansible playbook to setup configuration..."
-  if [ ! -z ${ANSIBLE_TAGS} ]; then
-    ansible-playbook macbuild.yml --inventory=hosts --ask-become-pass --tags "${ANSIBLE_TAGS}"
-  else
-    ansible-playbook macbuild.yml --inventory=hosts --ask-become-pass
+  # Install Homebrew packages
+  if [[ -r ${MACBUILD_HOME}/brew_packages.lst ]]; then
+    log INFO "Installing Homebrew packages."
+    for pkg in $(cat ${MACBUILD_HOME}/brew_packages.lst); do
+      brew install ${pkg}
+    done
   fi
-  cd ${CWD}
+  if [[ -r ${MACBUILD_HOME}/cask_packages.lst ]]; then
+    log INFO "Installing Homebrew Cask packages."
+    for pkg in $(cat ${MACBUILD_HOME}/cask_packages.lst); do
+      brew install ${pkg}
+    done
+  fi
+
+  # Install NPM packages
+  if [[ -d ${MACBUILD_HOME}/npm_packages.lst ]]; then
+    log INFO "Installing NPM packages."
+    for pkg in $(cat ${MACBUILD_HOME}/npm_packages.lst); do
+      npm install --global ${pkg}
+    done
+  fi
 }
 
 # Process command line
@@ -148,31 +150,38 @@ for arg in "$@"; do
   fi
 
   case "$arg" in
-      -*=*) optarg=`echo "$arg" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
-      *) optarg= ;;
+  -*=*) optarg=$(echo "$arg" | sed 's/[-_a-zA-Z0-9]*=//') ;;
+  *) optarg= ;;
   esac
 
   case $arg in
-    -h | --help)
-      usage && exit 0
-      ;;
-    -i | --install)
-      MB_INSTALL="yes"
-      ;;
-    -r=* | --repo=*)
-      GIT_REPO="$optarg"
-      ;;
-    -t=* | --tags=*)
-      ANSIBLE_TAGS="$optarg"
-      ;;
-    -*)
-      echo "${red}Unknown option ${arg}, exiting...${reset}" && exit 1
-      ;;
-    *)
-      echo "${red}Unknown option or missing argument for ${arg}, exiting.${reset}"
-      usage
-      exit 1
-      ;;
+  -h | --help)
+    usage && exit 0
+    ;;
+  -i | --install)
+    MB_INSTALL="yes"
+    ;;
+  -h=* | --home=*)
+    MACBUILD_HOME="$optarg"
+    ;;
+  -l=* | --log-level=*)
+    MACBUILD_LOG_LEVEL="$optarg"
+    ;;
+  -r=* | --repo=*)
+    MACBUILD_REPO="$optarg"
+    ;;
+  -t=* | --tags=*)
+    ANSIBLE_TAGS="$optarg"
+    ;;
+  -*)
+    log ERROR "${red}Unknown option ${arg}, exit.${reset}"
+    exit 1
+    ;;
+  *)
+    log "${red}Unknown option or missing argument for ${arg}, exit.${reset}"
+    usage
+    exit 1
+    ;;
   esac
 done
 
